t1=("Fortaleza","Atlketico","Atletico","Bragantino","Bahia","Fluminense","Palmeiras","Flamengo","Atletico","Corinthians","Ceara","Santos","Cuiaba","Sport","Sao Paulo","Juventude","Internacional","Gremio","America","Chapecoense")
print(f"Os primeiros 5 colocados são os {t1[:5]}")
print(f"Os últimos 4 colocados {t1[16:]}")
alfa=sorted(t1)
print(alfa)
enc=t1.index("Chapecoense")
enc2=alfa.index("Chapecoense")
print(f"A Chapeccoense está na posição {enc} (na lista normal).")
print(f"A Chapeccoense está na posição {enc2} (na lista em ordem alfabetica).")